name: Flutter Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "$FIREBASE_TOKEN"
