name: Flutter Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git /opt/flutter
          echo "/opt/flutter/bin" >> $GITHUB_PATH  # Modificado para garantir a persistência no PATH
          export PATH="$PATH:/opt/flutter/bin"
          flutter --version  # Verifica a versão do Flutter para garantir que foi instalado corretamente
          flutter doctor  # Certifique-se de que o flutter está instalado corretamente

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "$FIREBASE_TOKEN"
